# Generated by Django 3.2.9 on 2021-12-05 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='feedback_correct',
        ),
        migrations.RemoveField(
            model_name='option',
            name='feedback_incorrect',
        ),
    ]
