# Generated by Django 3.2.9 on 2021-12-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='feedback',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
