# Generated by Django 3.2.9 on 2021-12-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_status'),
        ('questions', '0005_question_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=models.SET('Select Quiz'), related_name='questions', to='quiz.quiz'),
        ),
    ]
