# Generated by Django 3.2.9 on 2022-01-21 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_quiz_slug'),
        ('questions', '0007_alter_question_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option',
            field=models.CharField(max_length=500, verbose_name='option'),
        ),
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.CharField(max_length=900, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='quiz.quiz'),
        ),
    ]
