# Generated by Django 3.2.9 on 2022-02-06 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20220126_0813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['pk'], 'verbose_name_plural': 'Answer options'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('question', 'option')},
        ),
    ]
