# Generated by Django 3.2.9 on 2022-02-16 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_alter_question_body'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='option',
            unique_together=set(),
        ),
    ]
