# Generated by Django 3.2.9 on 2022-02-19 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_alter_option_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-updated_on']},
        ),
    ]
