# Generated by Django 3.2.9 on 2022-02-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_alter_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='feedback',
            field=models.CharField(blank=True, max_length=900),
        ),
    ]
