"""Urls for quiz app"""
from django.urls import path
from quiz import views

app_name = 'quiz'
urlpatterns = [
    path('', views.welcome_page_view, name='home'),
    path('quizzes/', views.QuizListView.as_view(), name='manage_quizzes'),
    path('quizzes/add_quiz/', views.CreateQuizView.as_view(), name='add_quiz'),
    path('quizzes/<slug:slug>/details/', views.QuizDetailsView.as_view(),
         name='quiz_details'),
    path('quizzes/<slug:slug>/edit_quiz/', views.EditQuizView.as_view(),
         name='edit_quiz'),
    path('quizzes/<slug:slug>/delete_quiz/', views.DeleteQuizView.as_view(),
         name='delete_quiz'),
    path('quizzes/<slug:slug>/toggle/', views.toggle_status, name='toggle'),
    path('quizzes/<slug:slug>/<int:pk>/remove_question/',
         views.remove_question_from_quiz, name='remove_question'),
    path('quizzes/<slug:slug>/<int:pk>/add_question/',
         views.add_question_to_quiz, name='add_question'),
    path('quizzes/add_category', views.AddCategoryInQuizView.as_view(),
         name='add_category_in_quiz'),
    # paths for views managing questions
    path('quizzes/<slug:slug>/add_question/',
         views.CreateQuestionInQuizView.as_view(),
         name='add_question_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/delete_question/',
         views.DeleteQuestionInQuizView.as_view(),
         name='delete_question_in_quiz'),
    # paths for views for editing question elements when accessed from quiz
    path('quizzes/<slug:slug>/<int:pk>/edit_question/',
         views.EditQuestionInQuizView.as_view(), name='edit_question_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/edit_question_text',
         views.EditQuestionText.as_view(), name='edit_question_text_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/edit_question_quiz',
         views.EditQuestionQuiz.as_view(), name='edit_question_quiz_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/edit_question_feedback',
         views.EditQuestionFeedback.as_view(),
         name='edit_question_feedback_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/edit_question_category',
         views.EditQuestionCategory.as_view(),
         name='edit_question_category_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/edit_question_image',
         views.EditQuestionImage.as_view(),
         name='edit_question_image_in_quiz'),
    # paths for viees managing options
    path('quizzes/<slug:slug>/<int:pk>/add_option/',
         views.CreateOptionInQuizView.as_view(), name='add_option_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/edit_option/',
         views.EditOptionInQuizView.as_view(), name='edit_option_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/delete_option/',
         views.DeleteOptionQuizView.as_view(), name='delete_option_in_quiz'),
    path('quizzes/<slug:slug>/<int:pk>/details/',
         views.QuestionDetailsInQuizView.as_view(),
         name='quiz_question_details'),
    ]
