# Generated by Django 3.2.9 on 2021-11-29 22:13

import cloudinary.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=250, unique=True)),
                ('answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('key', models.IntegerField(help_text='Correct answer')),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('featured_image', cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, verbose_name='image')),
                ('feedback_correct', models.CharField(max_length=200)),
                ('feedback_incorrect', models.CharField(max_length=220)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Approved')], default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question', to='quiz.category')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
    ]
