# Generated by Django 3.2.9 on 2021-12-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20211208_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
