# Generated by Django 3.2.9 on 2021-12-03 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20211202_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='slug',
        ),
        migrations.AddField(
            model_name='questionoptions',
            name='category',
            field=models.ManyToManyField(to='quiz.Category'),
        ),
        migrations.RemoveField(
            model_name='questionoptions',
            name='options',
        ),
        migrations.AddField(
            model_name='questionoptions',
            name='options',
            field=models.ManyToManyField(to='quiz.Option'),
        ),
        migrations.AlterField(
            model_name='questionoptions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='category',
        ),
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.ManyToManyField(related_name='quiz', to='quiz.Category'),
        ),
    ]
