# Generated by Django 3.2.9 on 2021-12-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20211203_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['position'], 'verbose_name_plural': 'Answer options'},
        ),
        migrations.AlterModelOptions(
            name='questionoptions',
            options={'verbose_name_plural': 'Items'},
        ),
        migrations.AddField(
            model_name='questionoptions',
            name='correct_answer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ManyToManyField(related_name='question', to='quiz.Category'),
        ),
    ]
