# Generated by Django 3.2.9 on 2021-12-13 18:06

from django.db import migrations, models
import uuid

def update_slugs(apps, schema_editor):
    SomeModel = apps.get_model("quiz", "Quiz")

    for instance in SomeModel.objects.all():
        instance.slug = '%s-%s' % (instance.slug, instance.object_id)
        instance.save()

class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_status'),
    ]

    operations = [
        migrations.RunPython(update_slugs, reverse_code=migrations.RunPython.noop),

        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, max_length=200, unique=True),
        ),
    ]
