# Generated by Django 3.2.9 on 2021-12-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_option'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['position'], 'verbose_name_plural': 'Answer Options'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='question',
            name='key',
        ),
        migrations.AddField(
            model_name='option',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='option',
            name='option',
            field=models.CharField(max_length=50, verbose_name='option'),
        ),
    ]
