# Generated by Django 3.2.9 on 2021-12-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
