# Generated by Django 3.2.9 on 2021-12-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20211201_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='feedback_correct',
        ),
        migrations.RemoveField(
            model_name='question',
            name='feedback_incorrect',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='feedback_correct',
            field=models.CharField(default='You are correct!', max_length=200),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='feedback_incorrect',
            field=models.CharField(default='Sorry, you got this wrong.', max_length=220),
        ),
    ]
